# -*- coding: utf-8 -*-
"""life_expectancy_analysis_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1emtD4v1jtzdvrskrlT3U8YSVrIACB9T0

# Life Expectancy Prediction
### WHO Global Health Data (2000-2015)

Analyzing factors affecting life expectancy across 193 countries using machine learning.

## 1. Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 11

print('Libraries loaded successfully')

"""## 2. Load Dataset"""

df = pd.read_csv('/content/Life_Expectancy_Data.csv')

print(f'Dataset shape: {df.shape}')
print(f'Countries: {df["Country"].nunique()}')
print(f'Years: {df["Year"].min()} to {df["Year"].max()}')

df.head()

df.info()

"""## 3. Data Exploration"""

# check missing values
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(1)
missing_info = pd.DataFrame({'count': missing, 'percent': missing_pct})
missing_info[missing_info['count'] > 0].sort_values('count', ascending=False)

# target variable
target = 'Life expectancy '

print('Life Expectancy Stats:')
print(f'  Mean: {df[target].mean():.1f} years')
print(f'  Median: {df[target].median():.1f} years')
print(f'  Min: {df[target].min():.1f} years')
print(f'  Max: {df[target].max():.1f} years')
print(f'  Std: {df[target].std():.1f} years')

# development status breakdown
print('Development Status:')
print(df['Status'].value_counts())
print(f'\nDeveloped: {(df["Status"] == "Developed").sum() / len(df) * 100:.1f}%')
print(f'Developing: {(df["Status"] == "Developing").sum() / len(df) * 100:.1f}%')

df.describe()

"""## 4. Data Visualization"""

# create visualizations folder
import os
os.makedirs('visualizations', exist_ok=True)

# 1. life expectancy distribution
fig, ax = plt.subplots(figsize=(10, 6))
ax.hist(df[target].dropna(), bins=35, color='#3498db', edgecolor='white', alpha=0.8)
ax.axvline(df[target].mean(), color='#e74c3c', linestyle='--', lw=2, label=f'Mean: {df[target].mean():.1f}')
ax.axvline(df[target].median(), color='#2ecc71', linestyle='--', lw=2, label=f'Median: {df[target].median():.1f}')
ax.set_xlabel('Life Expectancy (Years)')
ax.set_ylabel('Frequency')
ax.set_title('Distribution of Life Expectancy Across Countries')
ax.legend()
plt.tight_layout()
plt.savefig('visualizations/01_distribution.png', dpi=150)
plt.show()

# 2. boxplot by status
fig, ax = plt.subplots(figsize=(8, 6))
df.boxplot(column=target, by='Status', ax=ax, patch_artist=True)
plt.suptitle('')
ax.set_title('Life Expectancy: Developed vs Developing Countries')
ax.set_xlabel('Development Status')
ax.set_ylabel('Life Expectancy (Years)')
plt.tight_layout()
plt.savefig('visualizations/02_boxplot_status.png', dpi=150)
plt.show()

# 3. yearly trend
yearly = df.groupby('Year')[target].mean()

fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(yearly.index, yearly.values, marker='o', markersize=8, linewidth=2, color='#3498db')
ax.fill_between(yearly.index, yearly.values, alpha=0.2, color='#3498db')
ax.set_xlabel('Year')
ax.set_ylabel('Average Life Expectancy (Years)')
ax.set_title('Global Life Expectancy Trend (2000-2015)')
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('visualizations/03_yearly_trend.png', dpi=150)
plt.show()

# 4. trend by development status
fig, ax = plt.subplots(figsize=(10, 6))
for status, color in [('Developed', '#2ecc71'), ('Developing', '#e74c3c')]:
    data = df[df['Status'] == status].groupby('Year')[target].mean()
    ax.plot(data.index, data.values, marker='o', linewidth=2, label=status, color=color)

ax.set_xlabel('Year')
ax.set_ylabel('Average Life Expectancy (Years)')
ax.set_title('Life Expectancy Trend by Development Status')
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('visualizations/04_trend_by_status.png', dpi=150)
plt.show()

# 5. correlation heatmap
numeric_cols = df.select_dtypes(include=[np.number]).columns
corr = df[numeric_cols].corr()

fig, ax = plt.subplots(figsize=(14, 12))
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='RdYlBu_r',
            center=0, square=True, linewidths=0.5, ax=ax,
            annot_kws={'size': 8}, cbar_kws={'shrink': 0.8})
ax.set_title('Correlation Matrix', fontsize=14, pad=15)
plt.tight_layout()
plt.savefig('visualizations/05_correlation_heatmap.png', dpi=150)
plt.show()

# 6. feature correlations with life expectancy
life_corr = corr[target].drop(target).sort_values()

fig, ax = plt.subplots(figsize=(10, 8))
colors = ['#e74c3c' if x < 0 else '#2ecc71' for x in life_corr.values]
ax.barh(life_corr.index, life_corr.values, color=colors)
ax.axvline(x=0, color='black', linewidth=0.5)
ax.set_xlabel('Correlation Coefficient')
ax.set_title('Feature Correlations with Life Expectancy')
plt.tight_layout()
plt.savefig('visualizations/06_feature_correlations.png', dpi=150)
plt.show()

# 7. scatter plots for key features
key_features = ['Schooling', 'Income composition of resources', 'Adult Mortality', ' HIV/AIDS']

fig, axes = plt.subplots(2, 2, figsize=(12, 10))
axes = axes.flatten()

for i, feat in enumerate(key_features):
    if feat in df.columns:
        axes[i].scatter(df[feat], df[target], alpha=0.4, s=20, c='#3498db')
        corr_val = df[[feat, target]].corr().iloc[0, 1]
        axes[i].set_xlabel(feat.strip())
        axes[i].set_ylabel('Life Expectancy')
        axes[i].set_title(f'r = {corr_val:.3f}')
        axes[i].grid(True, alpha=0.3)

plt.suptitle('Life Expectancy vs Key Predictors', fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig('visualizations/07_scatter_plots.png', dpi=150)
plt.show()

# 8. outlier detection
outlier_cols = ['Adult Mortality', 'infant deaths', 'GDP', ' HIV/AIDS',
                'Alcohol', 'Measles ', 'Population', ' BMI ']

fig, axes = plt.subplots(2, 4, figsize=(16, 8))
axes = axes.flatten()

for i, col in enumerate(outlier_cols):
    if col in df.columns:
        axes[i].boxplot(df[col].dropna(), patch_artist=True,
                       boxprops=dict(facecolor='#3498db', alpha=0.7))
        axes[i].set_title(col.strip(), fontsize=10)
        axes[i].grid(True, alpha=0.3)

plt.suptitle('Outlier Detection', fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig('visualizations/08_outliers.png', dpi=150)
plt.show()

"""## 5. Data Cleaning"""

df_clean = df.copy()
print(f'Original missing values: {df_clean.isnull().sum().sum()}')

# fill missing values with mean
numeric_cols = df_clean.select_dtypes(include=[np.number]).columns
imputer = SimpleImputer(strategy='mean')

for col in numeric_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col] = imputer.fit_transform(df_clean[[col]])

print(f'Missing values after imputation: {df_clean.isnull().sum().sum()}')

# handle outliers using IQR method
outlier_cols = ['Adult Mortality', 'infant deaths', 'Alcohol', 'percentage expenditure',
                'Hepatitis B', 'Measles ', ' BMI ', 'under-five deaths ', 'Polio',
                'Total expenditure', 'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
                ' thinness  1-19 years', ' thinness 5-9 years',
                'Income composition of resources', 'Schooling']

outliers_fixed = 0
for col in outlier_cols:
    if col in df_clean.columns:
        q1 = df_clean[col].quantile(0.25)
        q3 = df_clean[col].quantile(0.75)
        iqr = q3 - q1
        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        outliers = ((df_clean[col] < lower) | (df_clean[col] > upper)).sum()
        outliers_fixed += outliers

        col_mean = df_clean[col].mean()
        df_clean[col] = np.where((df_clean[col] < lower) | (df_clean[col] > upper),
                                  col_mean, df_clean[col])

print(f'Outliers replaced: {outliers_fixed}')

# encode categorical variables
le = LabelEncoder()
df_clean['Status_Encoded'] = le.fit_transform(df_clean['Status'])
df_clean['Country_Encoded'] = le.fit_transform(df_clean['Country'])

print('Encoding:')
print('  Developed = 0')
print('  Developing = 1')

# create new features
df_clean['Mortality_Ratio'] = df_clean['Adult Mortality'] / (df_clean['infant deaths'] + 1)
df_clean['Immunization_Score'] = (df_clean['Polio'] + df_clean['Diphtheria '] + df_clean['Hepatitis B']) / 3
df_clean['GDP_Income'] = df_clean['GDP'] * df_clean['Income composition of resources']

print('New features created:')
print('  - Mortality_Ratio')
print('  - Immunization_Score')
print('  - GDP_Income')

# save cleaned data
os.makedirs('cleaned_data', exist_ok=True)
df_clean.to_csv('cleaned_data/life_expectancy_cleaned.csv', index=False)
print('Saved: cleaned_data/life_expectancy_cleaned.csv')

df_clean.head()

"""## 6. Model Building"""

# prepare features
feature_cols = ['Year', 'Adult Mortality', 'infant deaths', 'Alcohol', 'percentage expenditure',
                'Hepatitis B', 'Measles ', ' BMI ', 'under-five deaths ', 'Polio',
                'Total expenditure', 'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
                ' thinness  1-19 years', ' thinness 5-9 years', 'Income composition of resources',
                'Schooling', 'Status_Encoded', 'Mortality_Ratio', 'Immunization_Score', 'GDP_Income']

feature_cols = [c for c in feature_cols if c in df_clean.columns]

X = df_clean[feature_cols]
y = df_clean[target]

print(f'Features: {len(feature_cols)}')
print(f'Samples: {len(X)}')

# scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# train test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print(f'Training samples: {len(X_train)}')
print(f'Test samples: {len(X_test)}')

# train multiple models
models = {
    'Linear Regression': LinearRegression(),
    'Ridge': Ridge(alpha=1.0),
    'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
    'Extra Trees': ExtraTreesRegressor(n_estimators=100, random_state=42, n_jobs=-1),
    'Gradient Boosting': GradientBoostingRegressor(n_estimators=100, random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    r2 = r2_score(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)

    results.append({
        'Model': name,
        'R2_Score': round(r2, 4),
        'RMSE': round(rmse, 4),
        'MAE': round(mae, 4)
    })
    print(f'{name}: R² = {r2:.4f}, RMSE = {rmse:.2f}')

results_df = pd.DataFrame(results).sort_values('R2_Score', ascending=False)
results_df

# save model results
results_df.to_csv('cleaned_data/model_results.csv', index=False)
print('Saved: cleaned_data/model_results.csv')

# best model
best_model_name = results_df.iloc[0]['Model']
best_model = models[best_model_name]

print(f'Best Model: {best_model_name}')
print(f'R² Score: {results_df.iloc[0]["R2_Score"]}')
print(f'RMSE: {results_df.iloc[0]["RMSE"]} years')

# cross validation
cv_scores = cross_val_score(best_model, X_scaled, y, cv=10, scoring='r2')

print('10-Fold Cross Validation:')
print(f'  Mean R²: {cv_scores.mean():.4f}')
print(f'  Std: {cv_scores.std():.4f}')
print(f'  Min: {cv_scores.min():.4f}')
print(f'  Max: {cv_scores.max():.4f}')

"""## 7. Model Evaluation"""

# 9. model comparison
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

colors = ['#2ecc71' if m == best_model_name else '#3498db' for m in results_df['Model']]

# R2 scores
axes[0].barh(results_df['Model'], results_df['R2_Score'], color=colors)
axes[0].set_xlabel('R² Score')
axes[0].set_title('Model Comparison - R² Score')
axes[0].set_xlim(0.8, 1.0)
for i, v in enumerate(results_df['R2_Score']):
    axes[0].text(v + 0.005, i, f'{v:.4f}', va='center', fontsize=9)

# RMSE
axes[1].barh(results_df['Model'], results_df['RMSE'], color=colors)
axes[1].set_xlabel('RMSE (Years)')
axes[1].set_title('Model Comparison - RMSE')
for i, v in enumerate(results_df['RMSE']):
    axes[1].text(v + 0.05, i, f'{v:.2f}', va='center', fontsize=9)

plt.tight_layout()
plt.savefig('visualizations/09_model_comparison.png', dpi=150)
plt.show()

# 10. feature importance
if hasattr(best_model, 'feature_importances_'):
    importance = pd.DataFrame({
        'Feature': feature_cols,
        'Importance': best_model.feature_importances_
    }).sort_values('Importance', ascending=True)

    importance.sort_values('Importance', ascending=False).to_csv('cleaned_data/feature_importance.csv', index=False)

    fig, ax = plt.subplots(figsize=(10, 10))
    ax.barh(importance['Feature'], importance['Importance'], color='#3498db')
    ax.set_xlabel('Importance')
    ax.set_title(f'Feature Importance - {best_model_name}')
    plt.tight_layout()
    plt.savefig('visualizations/10_feature_importance.png', dpi=150)
    plt.show()

    print('Saved: cleaned_data/feature_importance.csv')

# top 10 important features
importance.sort_values('Importance', ascending=False).head(10)

# 11. actual vs predicted
y_pred_best = best_model.predict(X_test)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# scatter
axes[0].scatter(y_test, y_pred_best, alpha=0.5, s=30, c='#3498db')
axes[0].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
axes[0].set_xlabel('Actual Life Expectancy')
axes[0].set_ylabel('Predicted Life Expectancy')
axes[0].set_title('Actual vs Predicted')
axes[0].grid(True, alpha=0.3)

# residuals
residuals = y_test - y_pred_best
axes[1].scatter(y_pred_best, residuals, alpha=0.5, s=30, c='#3498db')
axes[1].axhline(y=0, color='r', linestyle='--', lw=2)
axes[1].set_xlabel('Predicted Life Expectancy')
axes[1].set_ylabel('Residuals')
axes[1].set_title('Residuals Plot')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('visualizations/11_predictions.png', dpi=150)
plt.show()

# 12. cross validation plot
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(range(1, 11), cv_scores, marker='o', linewidth=2, markersize=8, color='#3498db')
ax.axhline(cv_scores.mean(), color='#e74c3c', linestyle='--', lw=2, label=f'Mean: {cv_scores.mean():.4f}')
ax.fill_between(range(1, 11), cv_scores.mean() - cv_scores.std(), cv_scores.mean() + cv_scores.std(),
                alpha=0.2, color='#3498db')
ax.set_xlabel('Fold')
ax.set_ylabel('R² Score')
ax.set_title('10-Fold Cross Validation Results')
ax.set_xticks(range(1, 11))
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('visualizations/12_cross_validation.png', dpi=150)
plt.show()

"""## 8. Statistical Analysis"""

# t-test: developed vs developing
developed = df_clean[df_clean['Status'] == 'Developed'][target]
developing = df_clean[df_clean['Status'] == 'Developing'][target]

t_stat, p_val = stats.ttest_ind(developed, developing)

print('T-Test: Developed vs Developing')
print(f'  Developed mean: {developed.mean():.2f} years')
print(f'  Developing mean: {developing.mean():.2f} years')
print(f'  Difference: {developed.mean() - developing.mean():.2f} years')
print(f'  T-statistic: {t_stat:.2f}')
print(f'  P-value: {p_val:.2e}')
print(f'  Result: {"Significant" if p_val < 0.05 else "Not Significant"} at α=0.05')

# top correlations
print('Top Positive Correlations with Life Expectancy:')
pos_corr = life_corr.sort_values(ascending=False).head(5)
for feat, val in pos_corr.items():
    print(f'  {feat.strip()}: {val:.3f}')

print('\nTop Negative Correlations with Life Expectancy:')
neg_corr = life_corr.sort_values().head(5)
for feat, val in neg_corr.items():
    print(f'  {feat.strip()}: {val:.3f}')

"""## 9. Summary"""

print('='*50)
print('PROJECT SUMMARY')
print('='*50)
print(f'''
Dataset: WHO Life Expectancy Data
Countries: 193
Records: {len(df):,}
Period: 2000-2015

Best Model: {best_model_name}
R² Score: {results_df.iloc[0]["R2_Score"]:.4f} ({results_df.iloc[0]["R2_Score"]*100:.1f}% accuracy)
RMSE: {results_df.iloc[0]["RMSE"]:.2f} years
Cross-Validation R²: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}

Key Findings:
1. HIV/AIDS has the strongest impact on life expectancy
2. Schooling and income composition are strong positive predictors
3. Developed countries live ~12 years longer than developing nations
4. Global life expectancy improved by ~4 years from 2000 to 2015

Files Generated:
- visualizations/ (12 PNG files)
- cleaned_data/life_expectancy_cleaned.csv
- cleaned_data/model_results.csv
- cleaned_data/feature_importance.csv
''')
print('='*50)